### ISSUE TITLE
Files need to be in root folder

### ISSUE THREAD

**Issue by papatistos** [YJPL/lean-canvas-for-obsidian#3]
Thanks for sharing this! I just wanted to let you know that the template only works if you put all files in the vault's root folder. Otherwise Obsidian won't find the files to display in the canvas. Not sure if this can be solved or whether it depends on some obsidian settings. Either way, it's not a big deal to just swap the missing files against the real ones manually.

**Comment by YJPL** [comment]
Indeed. After downloading the code folder from GitHub, pick the "open folder as vault" option in Obsidian. I'll update the readme to make that more clear.

<img width="516" alt="open folder as vault  in Obsidian" src="https://github.com/YJPL/lean-canvas-for-obsidian/assets/26725821/494896f1-658d-417f-8f2e-156b8dacf7fc">
